# -*- coding: utf-8 -*-
"""train_ai_detectors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t_cCrJOIMElgAtz8L2VpIgDOyNLKXlnm
"""

# provjeri GPU
import torch
print(torch.cuda.is_available())       # mora True
print(torch.cuda.get_device_name(0))   # npr. Tesla T4

# Commented out IPython magic to ensure Python compatibility.
# kloniraj repo
!git clone https://github.com/nikolija-cuckic/ai-text-detector.git
# %cd ai-text-detector

!pip install transformers torch scikit-learn matplotlib -q

!mkdir -p data
!wget -q -O data/hc3_all.jsonl \
  https://huggingface.co/datasets/Hello-SimpleAI/HC3/resolve/main/all.jsonl
!wc -l data/hc3_all.jsonl  # treba da ispiše ~24k

from google.colab import drive
drive.mount('/content/drive')

import sys
sys.path.append("..")

import os
import torch
from configs.config import DataConfig, LSTMConfig, TransformerConfig, BERTConfig
from data.dataset import build_dataloaders
from models.lstm_baseline import LSTMClassifier
from models.classifier import TransformerClassifier
from models.bert_classifier import BERTClassifier
from training.trainer import Trainer

torch.manual_seed(9)
torch.set_num_threads(4)       # za CPU, na Kaggle/Colab ovo ignorisi
torch.set_num_interop_threads(2)

# configs — prilagodi batch_size i num_workers za GPU
data_cfg = DataConfig(max_len=256, batch_size=64, num_workers=2)
lstm_cfg = LSTMConfig(max_epochs=20, patience=3)
trans_cfg = TransformerConfig(max_len=256, max_epochs=20, patience=3)
bert_cfg = BERTConfig(max_epochs=5, patience=2)

# dataloaders se grade jednom, dele sva 3 modela
train_loader, val_loader, test_loader, _ = build_dataloaders(
    batch_size=data_cfg.batch_size,
    max_len=data_cfg.max_len,
    val_split=data_cfg.val_split,
    test_split=data_cfg.test_split,
    num_workers=data_cfg.num_workers,
    seed=data_cfg.seed
)

# sacuvaj test loader za evaluate.py
os.makedirs("../results", exist_ok=True)
torch.save(test_loader, "../results/test_loader_256.pt")
print("Test loader saved.")

# Transformer
torch.manual_seed(9)
model_trans = TransformerClassifier(config=trans_cfg)
trainer_trans = Trainer(model_trans, trans_cfg, train_loader, val_loader, "transformer")
history_trans = trainer_trans.train()

# LSTM
torch.manual_seed(9)
model_lstm = LSTMClassifier(config=lstm_cfg)
trainer_lstm = Trainer(model_lstm, lstm_cfg, train_loader, val_loader, "lstm")
history_lstm = trainer_lstm.train()

model_bert.freeze_bert()
print(f"Trainable: {model_bert.count_parameters():,}")  # samo ~1538

# BERT
torch.manual_seed(9)
model_bert = BERTClassifier(config=bert_cfg)
trainer_bert = Trainer(model_bert, bert_cfg, train_loader, val_loader, "bert")
history_bert = trainer_bert.train()

import sys
sys.path.append("..")

import os
import torch
from configs.config import DataConfig, LSTMConfig, TransformerConfig, BERTConfig
from data.dataset import build_dataloaders
from models.lstm_baseline import LSTMClassifier
from models.classifier import TransformerClassifier
from models.bert_classifier import BERTClassifier
from training.trainer import Trainer

torch.manual_seed(9)
torch.set_num_threads(4)       # za CPU, na Kaggle/Colab ovo ignorisi
torch.set_num_interop_threads(2)

# configs — prilagodi batch_size i num_workers za GPU
data_cfg = DataConfig(max_len=128, batch_size=64, num_workers=2)
lstm_cfg = LSTMConfig(max_epochs=20, patience=3)
trans_cfg = TransformerConfig(max_len=128, max_epochs=20, patience=3)
bert_cfg = BERTConfig(max_epochs=5, patience=2)

# dataloaders se grade jednom, dele sva 3 modela
train_loader, val_loader, test_loader, _ = build_dataloaders(
    batch_size=data_cfg.batch_size,
    max_len=data_cfg.max_len,
    val_split=data_cfg.val_split,
    test_split=data_cfg.test_split,
    num_workers=data_cfg.num_workers,
    seed=data_cfg.seed
)

# sacuvaj test loader za evaluate.py
os.makedirs("../results", exist_ok=True)
torch.save(test_loader, "../results/test_loader_128.pt")
print("Test loader saved.")

# Transformer
torch.manual_seed(9)
model_trans = TransformerClassifier(config=trans_cfg)
trainer_trans = Trainer(model_trans, trans_cfg, train_loader, val_loader, "transformer")
history_trans = trainer_trans.train()

# LSTM
torch.manual_seed(9)
model_lstm = LSTMClassifier(config=lstm_cfg)
trainer_lstm = Trainer(model_lstm, lstm_cfg, train_loader, val_loader, "lstm")
history_lstm = trainer_lstm.train()

model_bert.freeze_bert()
print(f"Trainable: {model_bert.count_parameters():,}")  # samo ~1538

# BERT
torch.manual_seed(9)
model_bert = BERTClassifier(config=bert_cfg)
trainer_bert = Trainer(model_bert, bert_cfg, train_loader, val_loader, "bert")
history_bert = trainer_bert.train()

from scripts.evaluate import main
main()

import shutil

# kopiraj checkpoints i results na Drive
shutil.copytree(
    "checkpoints",
    "/content/drive/MyDrive/ai-text-detector/checkpoints",
    dirs_exist_ok=True
)
shutil.copytree(
    "results",
    "/content/drive/MyDrive/ai-text-detector/results",
    dirs_exist_ok=True
)

print("Saved to Drive")